---
bibliography: input/bib/jusmer.bib
csl: input/bib/apa6.csl
---

# Introduction

The pension system is at the core  of the welfare state, playing a key role in shaping income distribution among the elderly population [@esping-andersen_three_1990; @breznau_institutional_2023]. This system is based on a shared understanding that older adults require financial support after retirement, whereby pensions are designed to provide such  support. In such an understanding, justice principles held in a society are crucial, as they influence how individuals perceive the fairness of pension systems and the distribution of benefits in a society [@liebig_sociology_2016]. For instance, in systems that emphasize social solidarity, there may be a greater support towards redistributive mechanisms to ensure a more equitable distribution of pension benefits across different social groups. Conversely, in societies where meritocratic beliefs are prevalent, individuals may justify inequalities in pension benefits based on factors such as work history, contributions to the system, and individual effort [@mijs_paradox_2019; @castillo_socialization_2024]. 

The Chilean pension system is a classical case study when it comes to privatization based on individual contributions, whereby those with higher lifetime earnings tend to receive higher pension benefits, while those with lower earnings often face inadequate pensions. Such system has created large disparities and increased poverty rates among the elderly, making them struggle to make ends meet [@bril-mascarenhas_how_2019; @evans_assessing_2024; @cabib_avoiding_2025; @subsecretariadeprevisionsocial_percepcion_2023;@borzutzky_chiles_2016]. In this scenario, a deep discontent and social movements demanding reforms of the pension system have emerged in recent years. Nevertheless, and despite this discontent, some studies have shown that an important and growing share of the population is willing to justify inequalities in pensions based on individual contributions [@castillo_perceptions_2025]. In such a context, understanding how meritocratic beliefs and social class influence the justification of inequalities in pensions acquires relevance for informing policy debates and promoting social justice [@svallfors_moral_2006; @busemeyer_welfare_2020]. 

[market justice @juancarloscastillo]


The present paper aims to analyze how meritocratic beliefs and social class are associated with the justification of inequalities in pensions in Chile, and how these associations have evolved between 2016 and 2023. On the one hand, social class has been shown to influence individuals' perceptions of justice and fairness in various social contexts, including pensions, as it shapes their experiences and access to resources [@svallfors_moral_2006]. In this regard, individuals from higher social classes may be more likely to justify inequalities in pensions, as they may benefit more from the existing system. On the other hand, meritocracy is a widely held belief that individuals should be rewarded based on their abilities and efforts [@young_rise_1975; @mcnamee_meritocracy_2004]. In the context of pensions, this belief may lead individuals to justify inequalities in pension benefits based on their contributions to the system.

To address these issues, we utilize data from the Chilean Longitudinal Social Survey (ELSOC) conducted between 2016 and 2023. This survey provides a comprehensive overview of public attitudes towards social justice issues in Chile, including perceptions of pensions and income distribution. By analyzing this data, we aim to shed light on the complex interplay between meritocratic beliefs, social class, and the justification of inequalities in pensions in Chile over time. 

The paper is structured as follows. First, we review the relevant literature on meritocratic beliefs, social class, and the justification of inequalities in pensions. Next, we describe the data and methodology used in our analysis. We then present our findings on the associations between meritocratic beliefs, social class, and the justification of inequalities in pensions in Chile from 2016 to 2023. Finally, we discuss the implications of our findings for policy and future research.


