---
bibliography: "input/bib/jusmer.bib"
csl: "input/bib/apa6.csl"
---

# Market justice

In recent years, welfare states have undergone several institutional transformations, with market expansion strongly penetrating the field of social services and rights, while private alternatives emerge in parallel to public provision [@busemeyer_welfare_2020]. Such processes have led to changes in the architecture of the institutions responsible for social welfare, where private companies operate as service administrators that limit access based on the user's ability to pay, while public providers have reorganized to compete as quasi-markets [@lindh_it_2017]. Despite the commodification of services, this does not only apply changes at the formal level, but also shapes the beliefs of individuals. In this way, market-oriented policies can modify people's normative criteria, promoting or weakening support for different goods or services [@beland_varieties_2019 ; @jaime-castillo_public_2013]. 

In distributive justice field, market preferences have gained relevance in attitudinal studies on redistribution. In this context, market justice emerges as one of the central concepts in this literature, understood as a normative principle that legitimizes access to goods and services based on individual or family ability to pay, the basis of which is radically opposed to social justice [@lane_market_1986]. This market-oriented redistribution is closely related to the justification of inequalities, as it considers the market to be a space of equal opportunity, where economic success is understood as an individual outcome [@kluegel_legitimation_1999]. In this way, market justice legitimizes socioeconomic inequalities from an economic-moral perspective, ignoring the structural conditions that generate disparities. 

Research strategies on market preferences have focused on operationalizing this concept in order to empirically study how individuals' beliefs are shaped by macro-structural conditions, such as the application of privatization policies to goods such as education, health, or pensions [@lindh_public_2015; @kerner_pension_2020; @busemeyer_education_2013]. The inaugural study in this line of research was by @kluegel_beliefs_1981, analyzing the normative bases of beliefs about social stratification. Subsequently, market preferences have been studied in detail in surveys, asking how fair it is considered that those with higher incomes have access to better education, health, and/or pensions, respectively [@immergut_it_2020; @lindh_public_2015]. There are also studies that have measured market preferences using an index constructed from three items referring to market justice in the three main social services, operationalizing the concept of preferences for market justice [@castillo_perceptions_2025]. In short, all the strategies employed seek to understand the extent to which market-generated inequalities are legitimized.

Recent literature on market preferences has found striking associations with both individual and contextual factors. Various studies suggest that people with higher socioeconomic status tend to adopt greater market preferences than those who are in a more disadvantaged social position [@koos_moral_2019; @lindh_public_2015]. Similarly, political ideology has been linked to preferences for market justice, with right-wing individuals mostly supporting market-oriented distribution [@castillo_socialization_2024; @lee_fairness_2024]. These trends reflect a moral economy based on the justification of status by those who enjoy the benefits of the market. With regard to contextual factors, evidence suggests that in countries with greater private investment in services, individuals tend to decrease their preferences for redistribution, internalizing the market order as a criterion of justice, while in countries where public provision of services prevails, individuals show resistance to market-induced inequalities [@busemeyer_education_2013; @lindh_public_2015; @immergut_it_2020]. 

