---
title: "Market Justice and Stratification in Chile (2016-2023)"
format:
  docx:
    number-sections: true
  html: 
    code-fold: true
    html-math-method: katex
    number-sections: true
  pdf: 
    geometry: margin=2cm
    template-partials: 
      - title.tex
    keep-tex: true
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
    number-sections: true
editor: source
bibliography: "input/bib/merit-edjust.bib"
csl: "input/bib/apa6.csl"
author:
  - name: Juan Carlos Castillo
    corresponding: true
    orcid: 0000-0003-1265-7854
    email: juancastillov@uchile.cl
    affiliations:
      - ref: 1
      - ref: 2
      - ref: 3
  - name: Andreas Laffert
    orcid: 0000-0002-9008-2454
    email: alaffertt@estudiante.uc.cl 
    affiliations:
      - ref: 4
  - name: Kevin Carrasco
    orcid: 0000-0002-9348-8361
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 2
  - name: Julio Iturra
    orcid: 0000-0003-1993-3479
    email: julioiturrasanhueza@gmail.com 
    affiliations:
      - ref: 5     
affiliations: 
  - id: 1
    name: Departamento de Sociología, Universidad de Chile
  - id: 2
    name: Centro de estudios del conflicto y cohesión social (COES)
  - id: 3
    name: Núcleo milenio de desigualdades y oportunidades digitales (NUDOS)
  - id: 4
    name: Instituto de Sociología, Pontificia Universidad Católica de Chile
  - id: 5
    name: International Graduate School of Social Sciencies (BIGSSS), University of Bremen, Germany
citeproc: true
abstract: | 
  This study examines the interplay between perceptions of economic inequality and meritocracy in shaping preferences for market justice in Chile from 2016 to 2023. Economic inequality has intensified globally, raising concerns about its social impacts and the legitimacy of market-based distributions of resources. By utilizing longitudinal data from the Chilean Longitudinal Social Survey (ELSOC), the research investigates how subjective assessments of inequality influence attitudes towards social justice, focusing on the extent to which individuals believe access to essential services like healthcare, education, and pensions should depend on personal merit. The findings suggest that as perceptions of economic inequality rise, individuals tend to favor redistributive policies, although those with strong meritocratic beliefs are more likely to justify existing inequalities. The analysis also highlights the effect of major social movements in Chile during this period, which have shifted public discourse and potentially altered perceptions of inequality and meritocracy. This paper contributes to the understanding of how individual beliefs about fairness and equity evolve within a socio-political context characterized by high inequality and extensive free-market principles. 
  \newline
  **Keywords**: Economic inequality, meritocracy, market justice, Chile, public preferences
link-citations: true
linestretch: 1.15       
mainfont: Times New Roman
fontsize: 12pt          
colorlinks: true
fig-height: 4
fig-width: 7.5
---

```{r setup, include=FALSE}
 knitr::opts_chunk$set(echo=FALSE, warning = FALSE,message = FALSE, cache = TRUE,out.width = '85%',fig.pos= "H"
                       # , fig.align = 'center'
                       )
 # knitr::opts_knit$set(base.url = "../") #relative path for .html output file
 # knitr::opts_knit$set(root.dir = "../") #relative path for chunks within .rmd files
 options(scipen=999)
 options(kableExtra.auto_format = FALSE)
 rm(list=ls())
 options(knitr.kable.NA = '')
 options(knitr.graphics.error = FALSE)
 Sys.setlocale("LC_ALL", "ES_ES.UTF-8")
```

```{r}
# This document was last modified at {{< modified >}}
# 
# and it was last rendered at {{< now >}}

```


{{< include 01-introduction.qmd >}}

{{< include 02-antecedents.qmd >}}

{{< include 03-methods.qmd >}}

{{< include 04-analisis.qmd >}}

{{< include 05-discussion.qmd >}}

{{< include 06-conclusion.qmd >}}

# References

::: {#refs}
:::