# Methodology {background-color="#491106ff"}

## Data

::: {.incremental .highlight-last style="font-size: 120%;"}

- [ELSOC (COES)](https://coes.cl/elsoc/): a representative panel survey of the urban adult population in Chile, based on a probabilistic, stratified, clustered, and multistage sampling design across large and small cities

- Period: six waves (2016, 2017, 2018, 2019, 2022, and 2023)

- Attrition 2016→2023: ~ 40%

- Analytical sample (**balanced 6-wave panel**): 

    * **N = 5,755 observations** (level 1) nested within 
    * **N = 1,027 individuals** (level 2)

:::

## Estimation strategy

:::: {.incremental style="font-size: 110%;"}

**Cumulative link mixed models (CLMM)**:

- Panel structure: repeated observations (level 1) nested within individuals (level 2)

- Models both _within-person_ (WE) and _between-person_ (BE) effects; includes random effects (intercept and time slope)

- WE/BE decomposition (person-mean centering):

     * Within: $X^{WE}_{it}= X_{it}-\bar{X}_i$
     * Between: $X^{BE}_{i}=\bar{X}_i$

- Formally:  

::: {.fragment}
$$\begin{aligned}
\eta_{it} = \beta_{0}+ \beta_{1}\,\text{tiempo}_{it} +\beta_2\,\text{meritocracia}^{WE}_{it} +\beta_3\,{meritocracia}^{BE}_{i} +\beta_4\,\mathrm{EGP}_i +
    \end{aligned}$$
    
$$\beta_5\,(\mathrm{EGP}_i\!\times\! \text{meritocracia}^{WE}_{it}) +\beta_6\,(\mathrm{EGP}_i\!\times\! \text{meritocracia}^{BE}_{i}) +u_{0i}+u_{1i}\,\text{tiempo}_{it}\\$$
:::

::::


## Dependent variable
```{r}
#| label: fig-desc
#| fig-cap-location: top
#| fig-cap: "Distribution of responses for preferences for market justice in pensions in Chile (2016–2023)"
#| fig-align: center
#| out-width: '100%'
#| fig-asp: 0.6
#| echo: false

g1

```


## Independent variables: Level 1

:::: {.incremental style="font-size: 120%;"}

**Meritocracy**:

- Operationalized through two components: effort and talent [@young_rise_1958; @castillo_multidimensional_2023]

- Measurement (Likert 1–5):
  
    * “In Chile, people are rewarded for their effort.”
    * “In Chile, people are rewarded for their intelligence and ability.”

- Estimation of WE and BE effects [@singer_applied_2009; @bell_explaining_2015]
::::


## Independent variables: Level 2

:::: {.incremental style="font-size: 115%;"}
**Class position**: 

- Operationalized using the Erikson-Goldthorpe-Portocarrero (EGP) class scheme [-@eriksonCASMINProjectAmerican1992]

- Measurement → collapsed three-class version:
   
    * Service class (I+II)
    * Intermediate class (III+IV)
    * Working class (V+VI+VII)

- Additionally, three categories outside the labor force are included: retirees, unemployed respondents, and unpaid work
    
- Fixed at the first wave (i.e., time-invariant) → captures average between-person differences (BE = $\bar X_{i}$)

::::

