```{r}
#| echo: false
#| message: false
#| warning: false

library(knitr)
knitr::opts_chunk$set(echo = FALSE, 
                      include = TRUE, 
                      warning = FALSE, 
                      message = FALSE)

table_format <- if(is_html_output()) {
  "html"
} else if(is_latex_output()) {
  "latex"
}
table_format2 <- if(is_html_output()) {
  T
} else if(is_latex_output()) {
  F
}

options(kableExtra.html.bsTable = T)
options(knitr.kable.NA = "")
```


```{r}
#| include: false
#| echo: false
#| message: false

if (! require("pacman")) install.packages("pacman")

pacman::p_load(tidyverse, 
               sjmisc, 
               here, 
               performance,
               ordinal,
               texreg, 
               ggdist,
               sjlabelled,
               cowplot)


options(scipen=999)
rm(list = ls())
```


```{r}
#| echo: false
#| include: false

load(file = here("input/data/proc/df_balanced.RData"))

# Generate analytical sample

df_study1 <- df_balanced %>%
  select(-muestra) %>% 
  na.omit() %>% 
  mutate(ola = case_when(ola == 1 ~ 1,
                         ola == 2 ~ 2, 
                         ola == 3 ~ 3,
                         ola == 4 ~ 4,
                         ola == 6 ~ 5,
                         ola == 7 ~ 6)) %>% 
  mutate(ola = as.factor(ola),
         ola_num = as.numeric(ola),
         ola_2=as.numeric(ola)^2)

df_study1 <- df_study1 %>%
  group_by(idencuesta) %>%             # Agrupar por el identificador del participante
  mutate(n_participaciones = n()) %>%  # Contar el número de filas (participaciones) por participante
  ungroup()

df_study1 <- df_study1 %>% filter(n_participaciones>1)

# Corregir etiquetas

df_study1$just_pension <- sjlabelled::set_label(df_study1$just_pension, 
                        label = "Pension distributive justice")

df_study1$egp <- sjlabelled::set_label(df_study1$egp, 
                        label = "Social class")

df_study1$merit_effort <- sjlabelled::set_label(df_study1$merit_effort, 
                        label = "People are rewarded for their efforts")

df_study1$merit_talent <- sjlabelled::set_label(df_study1$merit_talent, 
                        label = "People are rewarded for their intelligence")

load(file = here("output/time_effects.RData"))
load(file = here("output/main_effects.RData"))
load(file = here("output/interactions_total.RData"))
load(file = here("output/interactions_direct.RData"))


```

# Results {background-color="#491106ff"}

## Models

```{r}
#| label: fig-model_time
#| fig-cap-location: top
#| fig-cap: "Efectos por ola en las preferencias por justicia de mercado en pensiones"
#| fig-align: center
#| out-width: '100%'
#| fig-asp: 0.5
#| echo: false

sjPlot::plot_model(
  m1.1,
  type = "est",
  terms = c("ola2017","ola2018","ola2019","ola2022","ola2023"),
  axis.labels = c("Wave 2023","Wave 2022","Wave 2019","Wave 2018","Wave 2017"),
  transform = NULL,
  show.ci = TRUE,     # <— muestra intervalos
  ci.lvl  = 0.95,     # <— nivel de confianza
  show.values = TRUE,
  p.style = "stars",
  vline.color = "grey40",
  value.size = 4.5
) +
  scale_y_continuous(limits = c(-1,1.5))+
  labs(title = NULL,
       caption = "*** p < 0.001; ** p < 0.01; * p < 0.05") +
  theme_ggdist() +
  theme(legend.position = "top",
        plot.title = element_text(face = "bold"),
        text = element_text(size = 16),
        plot.caption = element_text(size = 10, face = "italic")) 


```

::: {style="font-size: 80%;"}
- ICC = 0.23 between, 0.77 within
::::

## Models

```{r}
#| label: fig-model_be_we
#| fig-cap-location: top
#| fig-cap: "Efectos principales WE and BE en las preferencias por justicia de mercado en pensiones"
#| fig-align: center
#| out-width: '100%'
#| fig-asp: 0.6
#| echo: false

sjPlot::plot_model(
  m5,
  type = "est",
  terms = c("ola_num","ola_2", "egpIntermediate class (III+IV)","egpService class (I+II)","egpRetired or pensioner","egpUnemployed","egpPerforms unpaid tasks","merit_effort_cwc","merit_talent_cwc", "merit_effort_mean", "merit_talent_mean"),
  
   axis.labels = c("Merit: Talent (BE)",
                   "Merit: Effort (BE)",
                   "Merit: Talent (WE)",
                   "Merit: Effort (WE)",
                   "Performs unpaid tasks",
                   "Unemployed",
                   "Retired or pensioner",
                   "Service class (I+II)",
                   "Intermediate class (III+IV)",
                   "Wave^2",
                   "Wave"),
  transform = NULL,
  show.ci = TRUE,     # <— muestra intervalos
  ci.lvl  = 0.95,     # <— nivel de confianza
  show.values = TRUE,
  p.style = "stars",
  vline.color = "grey40",
  value.size = 4.5
) +
  scale_y_continuous(limits = c(-1,1.5))+
  labs(title = NULL,
       caption = "*** p < 0.001; ** p < 0.01; * p < 0.05") +
  theme_ggdist() +
  theme(legend.position = "top",
        plot.title = element_text(face = "bold"),
        text = element_text(size = 16),
        plot.caption = element_text(size = 10, face = "italic")) 



```

## Models

```{r}
#| label: fig-model_be_we_controls
#| fig-cap-location: top
#| fig-cap: "Efectos WE and BE en las preferencias por justicia de mercado en pensiones con controles"
#| fig-align: center
#| out-width: '100%'
#| fig-asp: 0.6
#| echo: false

sjPlot::plot_model(
  m6,
  type = "est",
  terms = c("ola_num","ola_2","egpIntermediate class (III+IV)","egpService class (I+II)","egpRetired or pensioner","egpUnemployed","egpPerforms unpaid tasks","merit_effort_cwc","merit_talent_cwc", "merit_effort_mean", "merit_talent_mean"),
  
   axis.labels = c("Merit: Talent (BE)",
                   "Merit: Effort (BE)",
                   "Merit: Talent (WE)",
                   "Merit: Effort (WE)",
                   "Performs unpaid tasks",
                   "Unemployed",
                   "Retired or pensioner",
                   "Service class (I+II)",
                   "Intermediate class (III+IV)",
                   "Wave^2",
                   "Wave"),
  transform = NULL,
  show.ci = TRUE,     # <— muestra intervalos
  ci.lvl  = 0.95,     # <— nivel de confianza
  show.values = TRUE,
  p.style = "stars",
  vline.color = "grey40",
  value.size = 4.5
) +
  scale_y_continuous(limits = c(-1,1.5))+
  labs(title = NULL, caption = "*** p < 0.001; ** p < 0.01; * p < 0.05") +
  theme_ggdist() +
  theme(legend.position = "top",
        plot.title = element_text(face = "bold"),
        text = element_text(size = 16),
        plot.caption = element_text(size = 10, face = "italic")) 
```


## Models

```{r}
#| label: fig-model_interactions
#| fig-cap-location: top
#| fig-cap: "Interacciones por clase, meritocracia y preferencias por justicia de mercado en pensiones"
#| fig-align: center
#| out-width: '100%'
#| fig-asp: 0.6
#| echo: false

library(broom.mixed)
library(broom)

df_pension <- bind_rows(
  tidy(m7, conf.int = TRUE) %>%
    filter(term %in% c("egpIntermediate class (III+IV):merit_effort_cwc", "egpService class (I+II):merit_effort_cwc")) %>%
    mutate(term = case_when(term == "egpIntermediate class (III+IV):merit_effort_cwc" ~ "Intermediate class (III+IV) x Merit: Effort (WE)",
                            term == "egpService class (I+II):merit_effort_cwc" ~ "Service class (I+II) x Merit: Effort (WE)"))
  ,
  tidy(m8, conf.int = TRUE) %>%
    filter(term %in% c("egpIntermediate class (III+IV):merit_talent_cwc", "egpService class (I+II):merit_talent_cwc")) %>%
    mutate(term = case_when(term == "egpIntermediate class (III+IV):merit_talent_cwc" ~ "Intermediate class (III+IV) x Merit: Talent (WE)",
                            term == "egpService class (I+II):merit_talent_cwc" ~ "Service class (I+II) x Merit: Talent (WE)"))
 ,
 tidy(m9, conf.int = TRUE) %>%
   filter(term %in% c("egpIntermediate class (III+IV):merit_effort_mean", "egpService class (I+II):merit_effort_mean")) %>%
   mutate(term = case_when(term == "egpIntermediate class (III+IV):merit_effort_mean" ~ "Intermediate class (III+IV) x Merit: Effort (BE)",
                           term == "egpService class (I+II):merit_effort_mean" ~ "Service class (I+II) x Merit: Effort (BE)"))
 ,
 tidy(m10, conf.int = TRUE) %>%
   filter(term %in% c("egpIntermediate class (III+IV):merit_talent_mean", "egpService class (I+II):merit_talent_mean")) %>%
   mutate(term = case_when(term == "egpIntermediate class (III+IV):merit_talent_mean" ~ "Intermediate class (III+IV) x Merit: Talent (BE)",
                           term == "egpService class (I+II):merit_talent_mean" ~ "Service class (I+II) x Merit: Talent (BE)"))
  
)

df_pension_lab <- df_pension %>%
  mutate(
    sig     = ifelse(conf.low * conf.high > 0, "*", ""),  # IC no cruza 0
    est_lab = sprintf("%.2f%s", estimate, sig),
    low_lab = sprintf("%.2f", conf.low),
    high_lab= sprintf("%.2f", conf.high)
  )

df_pension_lab <- df_pension_lab %>%
  mutate(
    term = factor(
      term,
      levels = term
      )
  )

ggplot(df_pension_lab, aes(x = estimate, y = term)) +
  geom_vline(xintercept = 0, linetype = "solid", color = "grey40", size = 0.5, alpha = 1) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0, color = "red") +
  geom_point(size = 3, color = "red") +
  scale_x_continuous(limits = c(-1, 1), breaks = seq(-1, 1, 0.5)) +
  geom_text(aes(label = est_lab), hjust = -0.2, size = 4, vjust = -0.5, color = "red") +
  labs(x = "Log-Odds", y = NULL,  caption = "*** p < 0.001; ** p < 0.01; * p < 0.05") +
  theme_ggdist() +
  theme(legend.position = "top",
        plot.title = element_text(face = "bold"),
        text = element_text(size = 16),
        plot.caption = element_text(size = 10, face = "italic")) 


# library(ggeffects)
# ggpredict(m10, terms = c("merit_talent_mean[meansd]", "egp"), type = "fixed") %>% plot()

```


