---
bibliography: "../input/bib/jusmer.bib"
csl: "../input/bib/apa6.csl"
---

## Meritocracy

Meritocracy is a normative principle that justifies the distribution of goods and services based on individual effort and talent, emphasizing that rewards should correspond to personal achievements rather than social status or inherited privileges [@young_rise_1975; @sandel_tyranny_2020]. This concept has gained prominence in contemporary societies, where meritocratic ideals are often invoked to legitimize socioeconomic inequalities, suggesting that individuals' success or failure is primarily determined by their own merits [@littler_meritocracy_2018]. Research on meritocratic beliefs has explored how individuals perceive the fairness of social systems that prioritize merit-based distribution. Such studies have shown that people who strongly endorse meritocratic ideals tend to justify existing inequalities, attributing success to personal effort and downplaying the role of structural factors such as social class [@reynolds_perceptions_2014]. This perspective can lead to reduced support for redistributive policies, as individuals may view such interventions as undermining the principles of meritocracy [@piketty_capital_2014]. In the same vein, it would be expected that people who believe more strongly in meritocracy would be more likely to justify inequalities in social domains, among them the pension system  [@castillo_multidimensional_2023].                                    

Empirical studies have examined the relationship between meritocratic  beliefs and various demographic and ideological factors. The role of contextual factors  have been focused on social mobility and economic inequality, as it would be expected that more mobile and equal society would favour meritocracy. Nevertheless, some evidence suggest that inequality would be actually related to larger meritocratic perceptions, referred as _the paradox of meritocracy_ [@mijs_paradox_2021] and linked to the policy-feedback literature mentioned above. Regarding individual factors, those with higher socioeconomic status are more likely to endorse meritocratic ideals, as they often benefit from systems that reward their efforts and talents [@harrs_fairness_2025]. Additionally, political ideology plays a significant role, with right-leaning individuals typically exhibiting stronger support for meritocracy compared to their left-leaning counterparts.  Overall, the concept of meritocracy remains a central theme in discussions about social justice and inequality, highlighting the complex interplay between individual effort, structural conditions, and societal values.

The measurement of meritocratic beliefs has been approached through various survey instruments that assess individuals' attitudes towards effort, talent, and the fairness of merit-based systems. Commonly used items include questions about the importance of hard work for success, the role of innate ability, and perceptions of fairness in competitive environments [@castillo_multidimensional_2023]. In the extant literature the measurement of meritocratic beliefs has often been inconsistent, with different studies employing varying scales and items, making cross-study comparisons challenging. To address this issue, some researchers have advocated for the development of standardized measures that capture the multifaceted nature of meritocratic beliefs. A first distinction to make here is the one between perceptions and preferences for meritocracy, usually the first being descriptive and the second more normative in nature [@castillo_multidimensional_2023]. Research on meritocratic perceptions have reveal that people's beliefs about the extent to which meritocracy exists in society can differ significantly from their normative support for meritocratic principles [@duru-bellat_whos_2012]. Besides, whereas meritocratic preferences are usually more consensual, meritocratic perceptions tend to vary more across individuals and contexts. Within this framework, in the present paper we will focus on the measurement of meritocratic perceptions, given our interest in understanding how individuals perceive the fairness of social systems that prioritize merit-based distribution.




