---
title: "Supplementary material"
format:
  html: 
    code-fold: true
    html-math-method: katex
    number-sections: true
  pdf: 
    geometry: margin=0.5cm
    template-partials: 
      - title.tex
    keep-tex: true
    number-sections: true
editor: source
link-citations: true
linestretch: 1.15       
mainfont: Times New Roman
fontsize: 12pt          
colorlinks: true
fig-height: 4
fig-width: 7.5
editor_options: 
  chunk_output_type: console
--- 

```{r}
#| echo: false
#| message: false
#| warning: false

library(knitr)
knitr::opts_chunk$set(echo = FALSE, 
                      include = TRUE, 
                      warning = FALSE, 
                      message = FALSE)

table_format <- if(is_html_output()) {
  "html"
} else if(is_latex_output()) {
  "latex"
}
table_format2 <- if(is_html_output()) {
  T
} else if(is_latex_output()) {
  F
}

options(kableExtra.html.bsTable = T)
options(knitr.kable.NA = "")
```


```{r}
#| include: false
#| echo: false
#| message: false

if (! require("pacman")) install.packages("pacman")

pacman::p_load(tidyverse, 
               sjmisc, 
               here, 
               texreg, 
               sjlabelled,
               ordinal,
               lme4,
               summarytools)


options(scipen=999)
rm(list = ls())
```


```{r}
#| echo: false
#| include: false

load(file = here("input/data/proc/df_balanced.RData"))
load(file = here("output/time_effects.RData"))
load(file = here("output/main_effects.RData"))
load(file = here("output/interactions_total.RData"))
load(file = here("output/interactions_direct.RData"))

# Generate analytical sample

df_study1 <- df_balanced %>%
  select(-muestra) %>% 
  na.omit() %>% 
  mutate(ola = case_when(ola == 1 ~ 1,
                         ola == 2 ~ 2, 
                         ola == 3 ~ 3,
                         ola == 4 ~ 4,
                         ola == 6 ~ 5,
                         ola == 7 ~ 6)) %>% 
  mutate(ola = as.factor(ola),
         ola_num = as.numeric(ola),
         ola_2=as.numeric(ola)^2)

df_study1 <- df_study1 %>%
  group_by(idencuesta) %>%             # Agrupar por el identificador del participante
  mutate(n_participaciones = n()) %>%  # Contar el número de filas (participaciones) por participante
  ungroup()

df_study1 <- df_study1 %>% filter(n_participaciones>1)

# Corregir etiquetas

df_study1$just_pension <- sjlabelled::set_label(df_study1$just_pension, 
                        label = "Pension distributive justice")

df_study1$egp <- sjlabelled::set_label(df_study1$egp, 
                        label = "Social class")

df_study1$merit_effort <- sjlabelled::set_label(df_study1$merit_effort, 
                        label = "People are rewarded for their efforts")

df_study1$merit_talent <- sjlabelled::set_label(df_study1$merit_talent, 
                        label = "People are rewarded for their intelligence")

```

```{r}
#| include: false

df_study1$merit_effort <- as_numeric(df_study1$merit_effort)
df_study1$merit_talent <- as_numeric(df_study1$merit_talent)

df_study1$merit_effort_dic <- if_else(df_study1$merit_effort <= 3, 0, 1)
df_study1$merit_talent_dic <- if_else(df_study1$merit_talent <= 3, 0, 1)

df_study1$age_2 <- (df_study1$age)^2 

df_study1 <- df_study1 %>% 
  mutate(ola = case_when(ola == 1 ~ "2016",
                         ola == 2 ~ "2017",
                         ola == 3 ~ "2018",
                         ola == 4 ~ "2019",
                         ola == 5 ~ "2022",
                         ola == 6 ~ "2023"),
         ola = factor(ola, levels = c("2016",
                                        "2017",
                                        "2018",
                                        "2019",
                                        "2022",
                                        "2023")))


df_study1 <- df_study1 %>% 
  group_by(idencuesta) %>% 
  mutate(merit_effort_mean = mean(merit_effort, na.rm = T),
         merit_effort_cwc = merit_effort - merit_effort_mean,
         merit_talent_mean = mean(merit_talent, na.rm = T),
         merit_talent_cwc = merit_talent - merit_talent_mean,
         merit_effort_dic_mean = mean(merit_effort_dic, na.rm = T),
         merit_effort_dic_cwc = merit_effort_dic - merit_effort_dic_mean,
         merit_talent_dic_mean = mean(merit_talent_dic, na.rm = T),
         merit_talent_dic_cwc = merit_talent_dic - merit_talent_dic_mean,
         ) %>% 
  ungroup()

df_study1$just_pension <- as_factor(df_study1$just_pension)

df_study1$egp <- factor(df_study1$egp, levels = c("Working class (V+VI+VII)",
                                                  "Intermediate class (III+IV)",
                                                  "Service class (I+II)",
                                                  "Retired or pensioner", 
                                                  "Unemployed",
                                                  "Performs unpaid tasks"))
```

```{r}
m0 <- clmm(just_pension ~ 1 + (1 | idencuesta), 
           link = "logit",
  Hess = TRUE, # calcula explícitamente la matriz varianza-covarianza de estimadores
                data = df_study1)

#performance::icc(m0, by_group = T) # 0.24 es between, 0.76 within
```

## Descriptive statistics for control variables

```{r}
#| label: tbl-summary-controls
#| tbl-cap: "Descriptive statistics for control variables for the last wave (2023)"
#| tbl-cap-location: top
#| results: asis
#| echo: false

t2 <- df_study1 %>% 
  filter(ola == "2023") %>% 
  select(educ,
         sex,
         age,
         ideo) 

t2$educ <- sjlabelled::set_label(t2$educ, "Educational level")
t2$sex <- sjlabelled::set_label(t2$sex, "Sex")
t2$age <- sjlabelled::set_label(t2$age, "Age")
t2$ideo <- sjlabelled::set_label(t2$ideo, "Political identification")


df<-dfSummary(t2,
               plain.ascii = FALSE,
               style = "multiline",
               tmp.img.dir = "/tmp",
               graph.magnif = 0.75,
               headings = F,  # encabezado
               varnumbers = F, # num variable
               labels.col = T, # etiquetas
               na.col = F,    # missing
               graph.col = F, # plot
               valid.col = T, # n valido
               col.widths = c(30,10,10,10))

df$Variable <- NULL # delete variable column

print(df)
```

## Complete longitudinal multilevel models


```{r echo=FALSE, results='asis'}

ccoef <- list(
  "Strongly disagree|Disagree" = "Strongly disagree|Disagree",
  "Disagree|Neither agree nor disagree" = "Disagree|Neither agree nor disagree",
  "Neither agree nor disagree|Agree" = "Neither agree nor disagree|Agree",
  "Agree|Strongly agree" = "Agree|Strongly agree",
  "ola2017" = "Wave 2017",
  "ola2018" = "Wave 2018",
  "ola2019" = "Wave 2019",
  "ola2022" = "Wave 2022",
  "ola2023" = "Wave 2023",
  ola_num = "Wave",
  ola_2 = "Wave^2",
  "egpIntermediate class (III+IV)" = "Intermediate class (III+IV)",
  "egpService class (I+II)" = "Service class (I+II)",
  "egpRetired or pensioner" = "Retired or pensioner",
  "egpUnemployed" = "Unemployed",
  "egpPerforms unpaid tasks" = "Performs unpaid tasks",
  merit_effort_cwc = "Merit: Effort (WE)",
  merit_talent_cwc = "Merit: Talent (WE)",
  merit_effort_mean = "Merit: Effort (BE)",
  merit_talent_mean = "Merit: Talent (BE)",
  "educUniversitary" = "Universitary education (Ref.= Less than Universitary)",
  ideoCenter = "Center",
  ideoRight = "Right",
  "ideoDoes not identify" = "Does not identify",
  sexFemale = "Female (Ref.= Male)",
  age = "Age (in years)"
  )

texreg::texreg(list(m0, m1.1, m1.4, m3, m4, m5, m6),
               custom.model.names = c("Model 0",paste0("Model ", seq(1:6))),
               caption = "Complete cumulative longitudinal multilevel models for pension market justice preferences",
               caption.above = T,
               stars = c(0.05, 0.01, 0.001),
               custom.coef.map = ccoef,
               digits = 3,
               groups = list("Wave (Ref.= 2016)" = 5:9,
                             "Social class (Ref.= Working class (V+VI+VII)" = 12:16,
                             "Political identification (Ref.= Left)" = 22:24),
               custom.note = "Note: Cells contain regression coefficients with standard errors in parentheses. %stars.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.7,
               include.loglik = FALSE,
               include.aic = FALSE,
               center = T,
               custom.gof.names = c("BIC", "Numb. obs.", "Num. groups: individuals", "Var: individuals (Intercept)", "Var: individuals, wave"))
              
```


```{r echo=FALSE, results='asis'}

ccoef <- list(
  #"Strongly disagree|Disagree" = "Strongly disagree|Disagree",
  #"Disagree|Neither agree nor disagree" = "Disagree|Neither agree nor disagree",
  #"Neither agree nor disagree|Agree" = "Neither agree nor disagree|Agree",
  #"Agree|Strongly agree" = "Agree|Strongly agree",
 # "egpIntermediate class (III+IV)" = "Intermediate class (III+IV)",
 # "egpService class (I+II)" = "Service class (I+II)",
 # "egpRetired or pensioner" = "Retired or pensioner",
 # "egpUnemployed" = "Unemployed",
 # "egpPerforms unpaid tasks" = "Performs unpaid tasks",
 # merit_effort_cwc = "Merit: Effort (WE)",
 # merit_talent_cwc = "Merit: Talent (WE)",
 # merit_effort_mean = "Merit: Effort (BE)",
 # merit_talent_mean = "Merit: Talent (BE)",
  
  "egpIntermediate class (III+IV):merit_effort_cwc" = "Intermediate class (III+IV) x Merit: Effort (WE)",
  "egpService class (I+II):merit_effort_cwc" = "Service class (I+II) x Merit: Effort (WE)",
   "egpRetired or pensioner:merit_effort_cwc" = "Retired or pensioner x Merit: Effort (WE)",
   "egpUnemployed:merit_effort_cwc" = "Unemployed x Merit: Effort (WE)",
   "egpPerforms unpaid tasks:merit_effort_cwc" = "Performs unpaid tasks x Merit: Effort (WE)",
  
  "egpIntermediate class (III+IV):merit_talent_cwc" = "Intermediate class (III+IV) x Merit: Talent (WE)",
"egpService class (I+II):merit_talent_cwc" = "Service class (I+II) x Merit: Talent (WE)",
"egpRetired or pensioner:merit_talent_cwc" = "Retired or pensioner x Merit: Talent (WE)",
"egpUnemployed:merit_talent_cwc" = "Unemployed x Merit: Talent (WE)",
"egpPerforms unpaid tasks:merit_talent_cwc" = "Performs unpaid tasks x Merit: Talent (WE)",
  
"egpIntermediate class (III+IV):merit_effort_mean" = "Intermediate class (III+IV) x Merit: Effort (BE)",
"egpService class (I+II):merit_effort_mean" = "Service class (I+II) x Merit: Effort (BE)",
"egpRetired or pensioner:merit_effort_mean" = "Retired or pensioner x Merit: Effort (BE)",
"egpUnemployed:merit_effort_mean" = "Unemployed x Merit: Effort (BE)",
"egpPerforms unpaid tasks:merit_effort_mean" = "Performs unpaid tasks x Merit: Effort (BE)",

"egpIntermediate class (III+IV):merit_talent_mean" = "Intermediate class (III+IV) x Merit: Talent (BE)",
"egpService class (I+II):merit_talent_mean" = "Service class (I+II) x Merit: Talent (BE)",
"egpRetired or pensioner:merit_talent_mean" = "Retired or pensioner x Merit: Talent (BE)",
"egpUnemployed:merit_talent_mean" = "Unemployed x Merit: Talent (BE)",
"egpPerforms unpaid tasks:merit_talent_mean" = "Performs unpaid tasks x Merit: Talent (BE)"
  )

texreg::texreg(list(m11,m12,m13,m14),
               custom.model.names = c("Model 7", "Model 8", "Model 9", "Model 10"),
               caption = "Interactions for social class, meritocracy, and pension market justice preferences",
               caption.above = T,
               stars = c(0.05, 0.01, 0.001),
               custom.coef.map = ccoef,
               digits = 3,
               groups = list("Social class (Ref.= Working class (V+VI+VII) x Meritocracy (WE)" = 1:10,
                              "Social class (Ref.= Working class (V+VI+VII) x Meritocracy (BE)" = 11:20),
               custom.note = "Note: Cells contain regression coefficients with standard errors in parentheses. %stars. CWC = centered within group.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.8,
               include.loglik = FALSE,
               include.aic = FALSE,
               center = T,
               custom.gof.names = c("BIC", 
                                    "Numb. obs.", 
                                    "Num. groups: individuals", 
                                    "Var: individuals (Intercept)", 
                                    "Var: individuals, wave",
                                    "Var: individuals, merit effort cwc", 
                                    "Var: individuals, merit talent cwc", 
                                    "Var: individuals, merit effort mean", 
                                    "Var: individuals, merit talent mean"
                                    ),
               custom.gof.rows = list("Controls"=c(rep("Yes",4))))

```

{{< pagebreak >}}

## Robustness check

```{r echo=FALSE, results='asis'}
load(file = here("output/robustness/time_effects.RData"))
load(file = here("output/robustness/main_effects.RData"))

ccoef <- list(
  "Strongly disagree|Disagree" = "Strongly disagree|Disagree",
  "Disagree|Neither agree nor disagree" = "Disagree|Neither agree nor disagree",
  "Neither agree nor disagree|Agree" = "Neither agree nor disagree|Agree",
  "Agree|Strongly agree" = "Agree|Strongly agree",
  "ola2017" = "Wave 2017",
  "ola2018" = "Wave 2018",
  "ola2019" = "Wave 2019",
  "ola2022" = "Wave 2022",
  "ola2023" = "Wave 2023",
  ola_num = "Wave",
  ola_2 = "Wave^2",
  "egpIntermediate class (III+IV)" = "Intermediate class (III+IV)",
  "egpService class (I+II)" = "Service class (I+II)",
  "egpRetired or pensioner" = "Retired or pensioner",
  "egpUnemployed" = "Unemployed",
  "egpPerforms unpaid tasks" = "Performs unpaid tasks",
  merit_effort_cwc = "Merit: Effort (WE)",
  merit_talent_cwc = "Merit: Talent (WE)",
  merit_effort_mean = "Merit: Effort (BE)",
  merit_talent_mean = "Merit: Talent (BE)",
  "educUniversitary" = "Universitary education (Ref.= Less than Universitary)",
  ideoCenter = "Center",
  ideoRight = "Right",
  "ideoDoes not identify" = "Does not identify",
  sexFemale = "Female (Ref.= Male)",
  age = "Age (in years)"
  )

texreg::texreg(list(m0, m1.1, m1.4, m3, m4, m5, m6),
               custom.model.names = c("Model 0",paste0("Model ", seq(1:6))),
               caption = "Cumulative longitudinal multilevel models for pension market justice preferences with unbalanced data",
               caption.above = T,
               stars = c(0.05, 0.01, 0.001),
               custom.coef.map = ccoef,
               digits = 3,
               groups = list("Wave (Ref.= 2016)" = 5:9,
                             "Social class (Ref.= Working class (V+VI+VII)" = 12:16,
                             "Political identification (Ref.= Left)" = 22:24),
               custom.note = "Note: Cells contain regression coefficients with standard errors in parentheses. %stars.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.7,
               include.loglik = FALSE,
               include.aic = FALSE,
               center = T,
               custom.gof.names = c("BIC", "Numb. obs.", "Num. groups: individuals", "Var: individuals (Intercept)", "Var: individuals, wave"))
              
```

```{r echo=FALSE, results='asis'}
load(file = here("output/robustness/interactions_direct.RData"))

ccoef <- list(
  #"Strongly disagree|Disagree" = "Strongly disagree|Disagree",
  #"Disagree|Neither agree nor disagree" = "Disagree|Neither agree nor disagree",
  #"Neither agree nor disagree|Agree" = "Neither agree nor disagree|Agree",
  #"Agree|Strongly agree" = "Agree|Strongly agree",
 # "egpIntermediate class (III+IV)" = "Intermediate class (III+IV)",
 # "egpService class (I+II)" = "Service class (I+II)",
 # "egpRetired or pensioner" = "Retired or pensioner",
 # "egpUnemployed" = "Unemployed",
 # "egpPerforms unpaid tasks" = "Performs unpaid tasks",
 # merit_effort_cwc = "Merit: Effort (WE)",
 # merit_talent_cwc = "Merit: Talent (WE)",
 # merit_effort_mean = "Merit: Effort (BE)",
 # merit_talent_mean = "Merit: Talent (BE)",
  
  "egpIntermediate class (III+IV):merit_effort_cwc" = "Intermediate class (III+IV) x Merit: Effort (WE)",
  "egpService class (I+II):merit_effort_cwc" = "Service class (I+II) x Merit: Effort (WE)",
   "egpRetired or pensioner:merit_effort_cwc" = "Retired or pensioner x Merit: Effort (WE)",
   "egpUnemployed:merit_effort_cwc" = "Unemployed x Merit: Effort (WE)",
   "egpPerforms unpaid tasks:merit_effort_cwc" = "Performs unpaid tasks x Merit: Effort (WE)",
  
  "egpIntermediate class (III+IV):merit_talent_cwc" = "Intermediate class (III+IV) x Merit: Talent (WE)",
"egpService class (I+II):merit_talent_cwc" = "Service class (I+II) x Merit: Talent (WE)",
"egpRetired or pensioner:merit_talent_cwc" = "Retired or pensioner x Merit: Talent (WE)",
"egpUnemployed:merit_talent_cwc" = "Unemployed x Merit: Talent (WE)",
"egpPerforms unpaid tasks:merit_talent_cwc" = "Performs unpaid tasks x Merit: Talent (WE)",
  
"egpIntermediate class (III+IV):merit_effort_mean" = "Intermediate class (III+IV) x Merit: Effort (BE)",
"egpService class (I+II):merit_effort_mean" = "Service class (I+II) x Merit: Effort (BE)",
"egpRetired or pensioner:merit_effort_mean" = "Retired or pensioner x Merit: Effort (BE)",
"egpUnemployed:merit_effort_mean" = "Unemployed x Merit: Effort (BE)",
"egpPerforms unpaid tasks:merit_effort_mean" = "Performs unpaid tasks x Merit: Effort (BE)",

"egpIntermediate class (III+IV):merit_talent_mean" = "Intermediate class (III+IV) x Merit: Talent (BE)",
"egpService class (I+II):merit_talent_mean" = "Service class (I+II) x Merit: Talent (BE)",
"egpRetired or pensioner:merit_talent_mean" = "Retired or pensioner x Merit: Talent (BE)",
"egpUnemployed:merit_talent_mean" = "Unemployed x Merit: Talent (BE)",
"egpPerforms unpaid tasks:merit_talent_mean" = "Performs unpaid tasks x Merit: Talent (BE)"
  )

texreg::texreg(list(m11,m12,m13,m14),
               custom.model.names = c("Model 7", "Model 8", "Model 9", "Model 10"),
               caption = "Interactions for social class, meritocracy, and pension market justice preferences with unbalanced data",
               caption.above = T,
               stars = c(0.05, 0.01, 0.001),
               custom.coef.map = ccoef,
               digits = 3,
               groups = list("Social class (Ref.= Working class (V+VI+VII) x Meritocracy (WE)" = 1:10,
                              "Social class (Ref.= Working class (V+VI+VII) x Meritocracy (BE)" = 11:20),
               custom.note = "Note: Cells contain regression coefficients with standard errors in parentheses. %stars. CWC = centered within group.",
               leading.zero = T,
               use.packages = F,
               booktabs = F,
               scalebox = 0.8,
               include.loglik = FALSE,
               include.aic = FALSE,
               center = T,
               custom.gof.names = c("BIC", 
                                    "Numb. obs.", 
                                    "Num. groups: individuals", 
                                    "Var: individuals (Intercept)", 
                                    "Var: individuals, wave",
                                    "Var: individuals, merit effort cwc", 
                                    "Var: individuals, merit talent cwc", 
                                    "Var: individuals, merit effort mean"
                                    ),
               custom.gof.rows = list("Controls"=c(rep("Yes",4))))

```