---
title: "Justification trajectories for pension inequality in Chile (2016-2023): The role of beliefs in meritocracy and social stratification"
format:
  docx:
    number-sections: true
  html: 
    code-fold: true
    html-math-method: katex
    number-sections: true
  pdf: 
    geometry: margin=2cm
    template-partials: 
      - title.tex
    keep-tex: true
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
    number-sections: true
    tbl-longtable: false
editor: source
bibliography: "../input/bib/jusmer.bib"
csl: "../input/bib/apa6.csl"
author:
  - name: Juan Carlos Castillo
    corresponding: true
    orcid: 0000-0003-1265-7854
    email: juancastillov@uchile.cl
    affiliations:
      - ref: 1
  - name: René Canales
    orcid: 0009-0002-4299-2725
    email: renecanales@uc.cl
    affiliations:
      - ref: 2    
  - name: Andreas Laffert
    orcid: 0000-0002-9008-2454
    email: alaffertt@estudiante.uc.cl 
    affiliations:
      - ref: 2
  - name: Tomás Urzúa
    orcid: 0009-0008-3167-6819
    email: tomas.urzua@ug.uchile.cl
    affiliations:
      - ref: 1
affiliations: 
  - id: 1
    name: Departament of Sociology, University of Chile
  - id: 2
    name: Institute of Sociology, Pontifical Catholic University of Chile
citeproc: true
abstract: | 
  My abstract
  \newline
  **Keywords**: Economic inequality, meritocracy, market justice, Chile, public preferences
link-citations: true
linestretch: 1.15       
mainfont: Times New Roman
fontsize: 12pt          
colorlinks: true
fig-height: 4
fig-width: 7.5
---

```{r setup, include=FALSE}
 knitr::opts_chunk$set(echo=FALSE, warning = FALSE,message = FALSE, cache = TRUE,out.width = '85%',fig.pos= "H"
                       # , fig.align = 'center'
                       )
 # knitr::opts_knit$set(base.url = "../") #relative path for .html output file
 # knitr::opts_knit$set(root.dir = "../") #relative path for chunks within .rmd files
 options(scipen=999)
 options(kableExtra.auto_format = FALSE)
 rm(list=ls())
 options(knitr.kable.NA = '')
 options(knitr.graphics.error = FALSE)
 Sys.setlocale("LC_ALL", "ES_ES.UTF-8")
```

```{r}
# This document was last modified at {{< modified >}}
# 
# and it was last rendered at {{< now >}}

```


{{< include 01-introduction.qmd >}}

{{< include 02-antecedents.qmd >}}

{{< include 03-methods.qmd >}}

{{< include 04-analisis.qmd >}}

{{< include 05-discussion.qmd >}}

{{< include 06-conclusion.qmd >}}

# References

::: {#refs}
:::